BankEmprestimoConsignado/Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BankEmprestimoConsignado.Data;
using BankEmprestimoConsignado.Models;
using Microsoft.AspNetCore.Authorization;
using BankEmprestimoConsignado.Extensions;
using BankEmprestimoConsignado.Business;

namespace BankEmprestimoConsignado.Controllers
{
    //[Authorize(Roles = "Gerente")]
    //[ClaimsAuthorize("gerente", "editar")]
    [Authorize]
    public class ClientesController : Controller
    {
        private readonly BankContext _context;
        private EmprestimoConsignado regrasNegocio;
        private readonly ApplicationUser usuario;
        public ClientesController(BankContext context)
        {
            _context = context;
           regrasNegocio = new EmprestimoConsignado();
        }

        // GET: Clientes
        //[AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Clientes.ToListAsync());
        }

        // GET: Clientes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes
                .FirstOrDefaultAsync(m => m.IdCliente == id);
            var lista = _context.Emprestimos.Where(c => c.IdCliente == cliente.IdCliente).ToList();
            cliente.Emprestimos = lista;
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // GET: Clientes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Clientes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdCliente,Nome,Cpf,Nascimento,Profissao,Margem,MargemCartao,Salario,Status")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cliente);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }

        // GET: Clientes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes.FindAsync(id);
            if (cliente == null)
            {
                return NotFound();
            }
            return View(cliente);
        }

        // POST: Clientes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdCliente,Nome,Cpf,Nascimento,Profissao,Margem,MargemCartao,Salario,Status")] Cliente cliente)
        {
            if (id != cliente.IdCliente)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cliente);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClienteExists(cliente.IdCliente))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }

        // GET: Clientes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes
                .FirstOrDefaultAsync(m => m.IdCliente == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // POST: Clientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cliente = await _context.Clientes.FindAsync(id);
            _context.Clientes.Remove(cliente);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClienteExists(int id)
        {
            return _context.Clientes.Any(e => e.IdCliente == id);
        }
    }
}

BankEmprestimoConsignado/Controllers/EmprestimosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BankEmprestimoConsignado.Data;
using BankEmprestimoConsignado.Models;
using BankEmprestimoConsignado.Business;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using BankEmprestimoConsignado.Extensions;

namespace BankEmprestimoConsignado.Controllers
{
    //[Authorize]
    [Authorize]
    public class EmprestimosController : Controller
    {
        private readonly BankContext _context;
        private EmprestimoConsignado regrasNegocio;
        private SignInManager<IdentityUser> SignInManager;
        private UserManager<IdentityUser> UserManager;
        public EmprestimosController(BankContext context)
        {
            _context = context;
           regrasNegocio = new EmprestimoConsignado();
        }

        // GET: Emprestimos
        //[AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            // Adicionados validação de usuário
            var usuarioId = User.Identity;
            var usuario = User.Claims.ToArray();
            //if (usuario[3].Type == "cliente")
            //{
            //    var emprestimoconsignadoContext = _context.Emprestimos.Include(e => e.IdClienteNavigation).Where(u => u.IdClienteNavigation == usuarioId);
            //    return View(await emprestimoconsignadoContext.ToListAsync());
            //}
            var bankContext = _context.Emprestimos.Include(e => e.IdClienteNavigation);
            return View(await bankContext.ToListAsync());
        }

        // GET: Emprestimos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var emprestimo = await _context.Emprestimos
                .Include(e => e.IdClienteNavigation)
                .FirstOrDefaultAsync(m => m.IdEmprestimo == id);
            if (emprestimo == null)
            {
                return NotFound();
            }

            return View(emprestimo);
        }

        // GET: Emprestimos/Create
        //[ClaimsAuthorize("gerente", "editar")]
        public IActionResult Create()
        {
            ViewData["IdCliente"] = new SelectList(_context.Clientes, "IdCliente", "Nome");
            return View();
        }

        // POST: Emprestimos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdEmprestimo,IdCliente,ValorLiberado,ValorEmprestimo,DataVenc,ValorParcela,QtdParcela,TaxaJuros,QtdParcelaRest,StatusEmprest,TipoEmprest")] Emprestimo emprestimo)
        {
            if (ModelState.IsValid)
            {
                //RetornaCliente(emprestimo.IdCliente);
                //if (regrasNegocio.PropostaDeEmprestimo(emprestimo.IdClienteNavigation, emprestimo.ValorEmprestimo, emprestimo.QtdParcela, emprestimo.TaxaJuros, emprestimo.TipoEmprest, emprestimo.DataVenc))
                //{

                //}
                _context.Add(emprestimo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdCliente"] = new SelectList(_context.Clientes, "IdCliente", "Nome", emprestimo.IdCliente);
            return View(emprestimo);
        }

        // GET: Emprestimos/Edit/5
        //[ClaimsAuthorize("gerente", "editar")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var emprestimo = await _context.Emprestimos.FindAsync(id);
            if (emprestimo == null)
            {
                return NotFound();
            }
            ViewData["IdCliente"] = new SelectList(_context.Clientes, "IdCliente", "Nome", emprestimo.IdCliente);
            return View(emprestimo);
        }

        // POST: Emprestimos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdEmprestimo,IdCliente,ValorLiberado,ValorEmprestimo,DataVenc,ValorParcela,QtdParcela,TaxaJuros,QtdParcelaRest,StatusEmprest,TipoEmprest")] Emprestimo emprestimo)
        {
            if (id != emprestimo.IdEmprestimo)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(emprestimo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmprestimoExists(emprestimo.IdEmprestimo))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdCliente"] = new SelectList(_context.Clientes, "IdCliente", "Nome", emprestimo.IdCliente);
            return View(emprestimo);
        }

        // GET: Emprestimos/Delete/5
        //[ClaimsAuthorize("gerente", "editar")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var emprestimo = await _context.Emprestimos
                .Include(e => e.IdClienteNavigation)
                .FirstOrDefaultAsync(m => m.IdEmprestimo == id);
            if (emprestimo == null)
            {
                return NotFound();
            }

            return View(emprestimo);
        }

        // POST: Emprestimos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var emprestimo = await _context.Emprestimos.FindAsync(id);
            _context.Emprestimos.Remove(emprestimo);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmprestimoExists(int id)
        {
            return _context.Emprestimos.Any(e => e.IdEmprestimo == id);
        }
        private Cliente RetornaCliente(int cpfCliente)
        {
            var cliente = _context.Clientes.FirstOrDefault(c => c.Cpf == cpfCliente);
            return cliente;
        }
    }
}

BankEmprestimoConsignado/Views/Shared/ListaEmprestimos.cshtml
@model BankEmprestimoConsignado.Models.Cliente

<p>
    <a asp-action="Create" asp-controller="Emprestimos">Criar emprestimo</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayName("Valor Liberado")
            </th>
            <th>
                @Html.DisplayName("Valor Emprestimo")
            </th>
            <th>
                @Html.DisplayName("Vencimento")
            </th>
            <th>
                @Html.DisplayName("Valor Parcela")
            </th>
            <th>
                @Html.DisplayName("Parcelas")
            </th>
            <th>
                @Html.DisplayName("Taxa")
            </th>
            <th>
                @Html.DisplayName("Parcelas Restant")
            </th>
            <th>
                @Html.DisplayName("Status")
            </th>
            <th>
                @Html.DisplayName("Tipo")
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Emprestimos) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ValorLiberado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ValorEmprestimo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataVenc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ValorParcela)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.QtdParcela)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TaxaJuros)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.QtdParcelaRest)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StatusEmprest)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TipoEmprest)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.IdEmprestimo">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.IdEmprestimo">Detalhes</a> |
                <a asp-action="Delete" asp-route-id="@item.IdEmprestimo">Deletar</a>
            </td>
        </tr>
}
    </tbody>
</table>

BankEmprestimoConsignado/Views/Shared/_Layout.cshtml
@using BankEmprestimoConsignado.Extensions
@{
   
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Patch Bank</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/Cliente.css"/>
    <link rel="stylesheet" href="~/front/codecss.css" media="screen">
    <link rel="stylesheet" href="~/front/Cliente.css" media="screen">
    @*<script class="u-script" type="text/javascript" src="/jquery.js" defer=""></script>
    <script class="u-script" type="text/javascript" src="/codejs.js" defer=""></script>*@
    <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i">
    <link href="~/images/f620ff6d1eb44ce1adf9d4da0b5c40b1.png"/>
    <script type="application/ld+json">{
		"@Context": "http://schema.org",
		"name": "Emprestimo Consignado",
		"logo": "~/images/f620ff6d1eb44ce1adf9d4da0b5c40b1.png"}</script>
    <meta name="theme-color" content="#104e92">
    <meta property="og:title" content="Cliente">
    <meta property="og:description" content="">
    <meta property="og:type" content="website">
    
</head>


<body class="u-body">
    <header class=" u-clearfix u-header u-section-row-container" id="sec-e2e7" data-animation-name="" data-animation-duration="0" data-animation-delay="0" data-animation-direction="">
      <div class="u-section-rows">
        <div class="u-custom-color-2 u-section-row u-section-row-1" id="sec-71fa">
          <div class="u-clearfix u-sheet ">
            <a class="container-1 u-image u-image-1" data-image-width="50" data-image-height="50" asp-area="" asp-controller="Home" asp-action="Index">
              <img src="~/images/f620ff6d1eb44ce1adf9d4da0b5c40b1.png" class="u-logo-image" data-image-width="80" alt="Logo do Banco">
            </a>
            <div class="entradaUser">
                <partial name="_LoginPartial">
            </div>
             @*
             <partial name="_OpcoesMenu">*@
            <h5> </h5>
          </div> 
        </div>
        <div class="u-custom-color-1 u-section-row u-section-row-2" id="sec-13b1">
          <div class="u-clearfix u-sheet u-valign-middle u-sheet-2">
            <nav class= "u-offcanvas u-menu-1" data-responsive-from="MD" data-submenu-level="on-click">
              <div class="menu-collapse" style="font-size: 1rem; letter-spacing: 0px;">
                <a class="u-button-style u-custom-active-border-color u-custom-border u-custom-border-color u-custom-borders u-custom-hover-border-color u-custom-left-right-menu-spacing u-custom-text-active-color u-custom-text-color u-custom-text-hover-color u-custom-top-bottom-menu-spacing u-nav-link u-text-body-color" href="#" style="height: 24px; color: rgb(255, 255, 255) !important;">
                  <svg class="u-svg-link" preserveAspectRatio="xMidYMin slice" viewBox="0 0 124 124" style=""></svg>
                  <svg class="u-svg-content" viewBox="0 0 124 124" x="0px" y="0px" id="svg-995b" style="enable-background:new 0 0 124 124;"><g><path d="M112,6H12C5.4,6,0,11.4,0,18s5.4,12,12,12h100c6.6,0,12-5.4,12-12S118.6,6,112,6z"></path><path d="M112,50H12C5.4,50,0,55.4,0,62c0,6.6,5.4,12,12,12h100c6.6,0,12-5.4,12-12C124,55.4,118.6,50,112,50z"></path><path d="M112,94H12c-6.6,0-12,5.4-12,12s5.4,12,12,12h100c6.6,0,12-5.4,12-12S118.6,94,112,94z"></path></g></svg>
                </a>
              </div>
              <div class="u-custom-menu u-nav-container">
                <ul class="u-nav u-spacing-30 u-unstyled u-nav-1">
                  <li class="u-nav-item">
                    <a class="u-border-2 u-border-active-black u-border-hover-black u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-black u-text-black u-text-hover-black" asp-area="" asp-controller="Clientes" asp-action="Index" style="padding: 6px 0px;">Cliente</a>
                  </li>
                  <li class="u-nav-item">
                    <a class="u-border-2 u-border-active-black u-border-hover-black u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-black u-text-black u-text-hover-black" asp-area="" asp-controller="Emprestimos" asp-action="Index" style="padding: 6px 0px;">Emprestimo</a>
                  </li>
                  </ul>
              </div>
              <div class="u-custom-menu u-nav-container-collapse">
                <div class="u-container-style u-custom-color-3 u-inner-container-layout u-sidenav">
                  <div class="u-inner-container-layout u-sidenav-overflow">
                    <div class="u-menu-close"></div>
                    <ul class="u-align-center u-nav u-popupmenu-items u-text-body-color u-unstyled u-nav-2">
                      <li class="u-nav-item">
                        <a class="u-button-style u-nav-link" asp-area="" asp-controller="Clientes" asp-action="Index" style="padding: 6px 0px;">Cliente</a>
                      </li>
                      <li class="u-nav-item">
                        <a class="u-button-style u-nav-link" asp-area="" asp-controller="Emprestimos" asp-action="Index" style="padding: 6px 0px;">Emprestimo</a>
                      </li>
                    </ul>
                  </div>
                </div>
                <div class="u-custom-color-1 u-menu-overlay u-opacity u-opacity-70"></div>
              </div>
            </nav>
          </div>
        </div>
      </div>
    </header>
 <style> 
.u-section-5 {
  min-height: 866px;
}

.u-logo-image .u-image .u-image-1{
    background-image: url("images/f620ff6d1eb44ce1adf9d4da0b5c40b1.png");
    
}

.u-section-5 .u-dialog-1 {
  width: 514px;
  min-height: 270px;
  box-shadow: 5px 5px 20px 0 rgba(0,0,0,0.4);
  margin: 284px auto 60px;
}

.u-section-5 .u-container-layout-1 {
  padding: 30px 30px 28px;
}

.u-section-5 .u-group-1 {
  min-height: 212px;
  background-image: none;
  margin-top: 0;
  margin-bottom: 0;
  box-shadow: 5px 5px 20px 0 rgba(0,0,0,0.4);
}

.u-section-5 .u-container-layout-2 {
  padding: 30px 29px 34px;
}

.u-section-5 .u-text-1 {
  font-weight: 700;
  text-transform: none;
  margin: 1px 1px 0;
}

.u-section-5 .u-text-2 {
  margin: 20px 25px 0 9px;
}

.u-section-5 .u-btn-1 {
  border-style: solid;
  font-weight: 700;
  font-size: 0.9375rem;
  margin: 24px auto 0 70px;
  padding: 6px 31px 6px 30px;
}

.u-section-5 .u-btn-2 {
  border-style: solid;
  font-weight: 700;
  font-size: 0.9375rem;
  margin: -39px auto -64px 233px;
  padding: 6px 31px 6px 30px;
}

.u-section-5 .u-icon-1 {
  width: 23px;
  height: 23px;
  left: auto;
  top: 7px;
  position: absolute;
  right: 7px;
}

  .u-section-5 .u-group-1 {
    min-height: 299px;
  }

  .u-section-5 .u-text-1 {
    margin-left: 0;
    margin-right: 0;
  }

  .u-section-5 .u-text-2 {
    margin-left: 24px;
    margin-right: 24px;
  }

  .u-section-5 .u-btn-1 {
    margin-left: 24px;
  }

  .u-section-5 .u-btn-2 {
    margin-right: 24px;
    margin-left: 59px;
  }
.container-1 {
   width: 700px; 
    margin-left: auto;
    margin-right: auto; 
    margin: 0 auto;
    width: 50%;
  }
 .entradaUser{
     align-items:center;
     margin-left: auto;
     margin-right: auto; 
     margin: 0 auto;
     
 }
</style>
          
    <main role="main" class="bd-content order-1 py-5" style="margin: 5em">

        @RenderBody()
    </main>
    <footer class="bd-footer py-5 mt-5 bg-light">
        <div class="container-1">
            <a class="u-image-1" data-image-width="200" data-image-height="200">
            <img src="~/images/f620ff6d1eb44ce1adf9d4da0b5c40b1.png" class="u-logo-image u-logo-image-1">
            </a>
            &copy; 2021 - CEC - Concessão de empréstimo consignado - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

BankEmprestimoConsignado/Views/Shared/_OpcoesMenu.cshtml
<ul class="navbar-nav">
    <li class="nav-item">
        <a class="nav-link text-dark" supress-by-claim-name="gerente" supress-by-claim-value="editar" asp-area="" asp-controller="Clientes" asp-action="Index">Clientes</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" supress-by-claim-name="gerente" supress-by-claim-value="editar" asp-area="" asp-controller="Emprestimos" asp-action="Index">Emprestimos</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" supress-by-claim-name="cliente" supress-by-claim-value="editar"asp-area="" asp-controller="Emprestimos" asp-action="Index">Meus Emprestimos</a>
    </li>
</ul>